version: "3.7"

services:
  database:
    image: postgres
    container_name: database_party_app
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=10245477
      - POSTGRES_DB=party_app
    volumes:
      - pgdata:/data/postgres
    networks:
      - party_app_network

  app:
    build: .
    container_name: party_app
    ports:
      - 3333:3333
    volumes:
      - .:/user/app
    depends_on:
      - database
    networks:
      - party_app_network

volumes:
  pgdata:
    driver: local

networks:
  party_app_network:
    driver: bridge
